steps:
# Step 1: Build the Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-east1-docker.pkg.dev/tw-rd-data-wegun-hsia/docker-temp/test-build:dev01', '.' ]

# Step 2: Push the image to the Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-east1-docker.pkg.dev/tw-rd-data-wegun-hsia/docker-temp/test-build:dev01']


# Step 3: Deployment to Cloud Run after image is pushed
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'my-cloudbuild-test-service'
  - '--image'
  - 'asia-east1-docker.pkg.dev/tw-rd-data-wegun-hsia/docker-temp/test-build:dev01'
  - '--region'
  - 'asia-east1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'